
---
- hosts: all
  tasks:
    - name: Run apt-mirror
      shell:docker exec CONTAINER mysqldump --all-databases --single-transaction --quick --lock-tables=false > full-backup-$(date +%F).sql -u root -p=admin123
